[package]
name = "fg-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
rand = "*"
threadpool = "1.8.1"
parking_lot = "0.12.3"